//comparator
// let a=3;
// let b=5;
// console.log(a==b);
// console.log(b>a);
// console.log(a<b);
// let c="Anirudh";
// let d=40;
// console.log(c==d);
// let e=30;
// let f="30";
// g=Number(f);
// console.log(g==e);
// let h=10;
// let i="10";
// console.log(h===i);
// console.log(null==undefined);
// console.log(null===undefined);
// console.log(null==0);
// console.log(null>=0);
// console.log(null<=0);
// console.log(null>0);
// console.log(null<0);
//undefine comparission
// console.log(undefined==0);
// console.log(undefined>=0);
// console.log(undefined<=0);
// console.log(undefined>0);
// console.log(undefined<0);
console.log(NaN==NaN);
let aa="rohit";
let bb="Anirudh";
console.log(aa==bb);
console.log(200>>3);
console.log(4&5);
console.log(11&14);
console.log(11|14);
console.log(5^7);
console.log(200<<2);
